[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
mpl-token-metadata = "4.1.2"
solana-program = "^1.16"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] } 

[workspace.package]
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/hardhatchad/ore"
readme = "./README.md"
keywords = ["solana", "crypto", "mining"]
